### ISSUE TITLE
Edge function exceed vercel plan limit

### ISSUE THREAD

**Issue by Breezelled** [Blazity/enterprise-commerce#30]
Hi Blazity guys!

When I try to deploy this commerce project directly into vercel, I encounter this error:

Error: The Edge Function "search.rsc" size is 1.01 MB and your plan size limit is 1 MB. Learn More: https://vercel.link/edge-function-size

The edge function exceed vercel free plan size limit, could you please help me to fix that? Thank you so much!

**Comment by bmstefanski** [comment]
Thanks for reporting the issue!

We'll take a look at that and get back to ASAP :) !

**Comment by bmstefanski** [comment]
It should now be fixed, please let us know! :)
